import express from "express";
import { cleanupExtraTimings, clearStuckBookings, getAllBookings, getAllShows, getDashboardData, getShowsByDate, isAdmin } from "../controllers/adminController.js";
import { protectAdmin } from "../middleware/auth.js";
import { resetAutoGeneratedShows } from "../controllers/adminMaintenanceController.js";

const adminRouter = express.Router();

adminRouter.get('/is-admin', protectAdmin, isAdmin)
adminRouter.get('/dashboard', protectAdmin, getDashboardData)
adminRouter.get('/all-shows', protectAdmin, getAllShows)
adminRouter.get('/all-bookings', protectAdmin, getAllBookings)
adminRouter.get("/shows-by-date", protectAdmin, getShowsByDate);
adminRouter.post("/booking/clear-stuck", protectAdmin, clearStuckBookings);
adminRouter.post(
    "/reset-auto-shows",
    protectAdmin,
    resetAutoGeneratedShows
);
adminRouter.get(
    "/reset-auto-shows",
    protectAdmin,
    resetAutoGeneratedShows
);

adminRouter.delete(
    '/cleanup-extra-timings',
    protectAdmin,
    cleanupExtraTimings
)

adminRouter.get(
    "/cleanup-extra-timings",
    protectAdmin,
    cleanupExtraTimings
);

export default adminRouter;