import mongoose from "mongoose";

const showSchema = new mongoose.Schema(
    {
        movie: {
            type: String,
            ref: "Movie",
            required: true,
        },
        theater: {
            type: mongoose.Schema.Types.ObjectId,
            ref: "Theater"
        },
        screenName: { type: String },
        experience: { type: String },
        showDateTime: { type: Date, required: true },
        showPrice: { type: Number, required: true },
        occupiedSeats: { type: Object, default: {} },
        isActive: { type: Boolean, default: true },
        hidden: { type: Boolean, default: false },
        format: {
            type: String,
            default: "2D",
        },
        experience: {
            type: String,
            default: "Standard",
        },
        language: {
            type: String,
            default: "English",
        },

        isAutoGenerated: { type: Boolean, default: false },
    }, { minimize: false, timestamps: true }
);
showSchema.index({ showDateTime: 1 });
showSchema.index({ movie: 1, showDateTime: 1 });
showSchema.index({ movie: 1, theater: 1, showDateTime: 1 });

const Show = mongoose.model("Show", showSchema);

export default Show;