// models/Show.js - Show schema for individual movie screenings
import mongoose from "mongoose";

const showSchema = new mongoose.Schema(
    {
        movie: {                                                    // Reference to Movie (TMDB ID string)
            type: String,
            ref: "Movie",
            required: true,
        },
        theater: {                                                  // Reference to Theater
            type: mongoose.Schema.Types.ObjectId,
            ref: "Theater"
        },
        screenName: { type: String },                               // Optional screen identifier
        experience: { type: String },                               // e.g., "Laser", "IMAX", "Dolby Atmos"
        showDateTime: { type: Date, required: true },               // Exact date and time of the screening
        showPrice: { type: Number, required: true },                // Ticket price for this show
        occupiedSeats: { type: Object, default: {} },               // Confirmed seats: { seatId: userId }
        isActive: { type: Boolean, default: true },                // Soft delete / disable flag
        hidden: { type: Boolean, default: false },                  // Admin can hide from user view
        format: {                                                   // Screening format
            type: String,
            default: "2D",
        },
        experience: {
            type: String,
            default: "Standard",
        },
        language: {
            type: String,
            default: "English",
        },

        isAutoGenerated: { type: Boolean, default: false },       // Flag for auto-scheduled shows
    }, { minimize: false, timestamps: true }
);

// Database indexes for efficient querying
showSchema.index({ showDateTime: 1 });                              // Sort/filter by date
showSchema.index({ movie: 1, showDateTime: 1 });                    // Movie schedule lookups
showSchema.index({ movie: 1, theater: 1, showDateTime: 1 });        // Unique show per theater slot

const Show = mongoose.model("Show", showSchema);

export default Show;