import Show from "../models/Show.js";
import Movie from "../models/Movie.js";

export const resetAutoGeneratedShows = async (req, res) => {
    try {
        const deletedShows = await Show.deleteMany({ isAutoGenerated: true });

        const updatedMovies = await Movie.updateMany(
            {},
            { $set: { autoShowsInitialized: false } }
        );

        return res.json({
            success: true,
            deletedAutoShows: deletedShows.deletedCount,
            moviesReset: updatedMovies.modifiedCount,
            message: "Auto-generated shows cleared & movies reset successfully",
        });
    } catch (err) {
        console.error("resetAutoGeneratedShows error:", err);
        return res.status(500).json({
            success: false,
            message: err.message,
        });
    }
};
